antecedent/patchwork

src/Interceptor.php
tests/applyScheduledPatchesOnlyOnce.phpt

In our project we use zend autoloader, so it's not easy control then class will be loaded, before or after I replace it's method. I found that if class loaded after, sometimes my replacement function call multiply time per one original method call.
That look like it's right to unset State::$scheduledPatches after them applied, but I'm not sure.

apply scheduled patches only once

---

src/Interceptor.php

```
$ php --version
HipHop VM 3.9.1 (rel)
Compiler: tags/HHVM-3.9.1-0-g0f72cfc2f0a01fdfeb72fbcfeb247b72998a66db
Repo schema: 6416960c150a4a4726fda74b659105ded8819d9c
```
When running our phpunit test suite on HHVM we noticed a bunch of failures and notices. A little digging proved that return values from functions patched with Patchwork were always `null`. 
Turns out the `$result` is not initialized and returned properly in the `fb_intercept` closure. This is what the patch addresses.

Fix return values from patched functions on HHVM

---

src/Utils.php

as it may cant' run the method in console env.

add function_exists('apc_clear_cache') for apc_clear_cache() execute

---

src/CallRerouting.php
tests/wildcard-class-instance.phpt

Currently when trying to use an instance of a class, you get the following error
```
Fatal error: Uncaught TypeError: Argument 2 passed to Patchwork\Utils\matchWildcard() must be of the type array, string given
```
This fixes the error by passing the correct arguments to the functions

Correctly handle class instances

---

src/CallRerouting.php
tests/constructor-with-parent-user-func.phpt
tests/includes/ConstructorWithParentUserFunc.php

This PR fixes invocations of call_user_func when calling the parent constructor. An example is included in the test.
```php
function __construct() {
call_user_func(['parent', '__construct']);
}
```

Fix call_user_func when calling parent constructor

---

src/CallRerouting.php
src/CodeManipulation/Actions/CallRerouting.php

When patching a function defined inside a file with `declare(strict_types=1);`, the following exception is thrown on the line with the opening brace of the function:
TypeError: debug_backtrace() expects parameter 1 to be integer, boolean given
This pull request fixes the issue by changing the argument to the correct type. The type was changed from `bool` to `int` in PHP 5.3.6. This fix also works for older versions of PHP, since `declare(strict_types=1);` was introduced in PHP 7.

Fix debug_backtrace argument type

---

.scrutinizer.yml
.travis.yml
src/Config.php

Problem is caused by the following:
Warning: Uncaught strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Make tests using patchwork running under PHP 7.3

---

tests/includes/TraitsWithAssertions.php
tests/traits.phpt

Calling static trait members directly instead via a class using the trait is deprecated as of PHP 8.1.
The functionality will still work until PHP 9.0.
With that in mind, I'm only adjusting the tests to silence the deprecation notice from the direct calls to trait methods.
I've chosen to do so by moving the problematic calls to a separate statement and silencing the method call there. This prevent an failing assertion accidentally being silenced and the test not reporting correctly.
Fixes 2 tests/10 warnings along the lines of:
```
Deprecated: Calling static trait method FooTrait::speak is deprecated, it should only be called on a class using the trait
```
Refs:
* https://wiki.php.net/rfc/deprecations_php_8_1#accessing_static_members_on_traits

PHP 8.1: fix tests for trait method replacement

---

src/CodeManipulation/Source.php

As of PHP 8.1, implicit conversion of a float value with a fractional part to integer, is deprecated.
In this case, `Source::match()` gets passed an offset, which _may_ not be an integer, while only strings and integers are allowed as array keys.
This means that PHP will automatically type juggle the float to an integer to be used for matching the array key.
As `$offset`, based on the above, theoretically can be either an integer or a string, making the conversion explicit by casting to integer may have the effect of destroying string keys.
Using a string cast is the more appropriate fix as integer keys passed as strings will then automatically be juggled to an integer by PHP anyway.
Fixes the following deprecation notice as can be seen when running the tests on PHP 8.1:
```
Deprecated: …
```

PHP 8.1: fix implicit float conversion

---

src/Utils.php

As of PHP 8.1, passing `null` to not explicitly nullable scalar parameters for PHP native functions is deprecated.
In this case, `$class` within `interpretCallable()` may be null, which leads to the following deprecation notice as can be seen when running the tests on PHP 8.1:
```
Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in path/to/patchwork/src/Utils.php on line 123
```
By handling `null` separately and setting `$class` to an empty string, the previous behaviour is maintained.
Refs:
* https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
* https://www.php.net/manual/en/function.ltrim.php

PHP 8.1: fix "passing null to non-nullable" [2]

---

src/CallRerouting.php

As of PHP 8.1, passing `null` to not explicitly nullable scalar parameters for PHP native functions is deprecated.
In this case, `$class` within `applyWildcard()` may be null, which leads to the following deprecation notice as can be seen when running the tests on PHP 8.1:
```
Deprecated: class_exists(): Passing null to parameter #1 ($class) of type string is deprecated in path/to/patchwork/src/CallRerouting.php on line 141
```
By handling `null` separately in the condition, the previous behaviour is maintained.
Refs:
* https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
* https://www.php.net/manual/en/function.class-exists.php

PHP 8.1: fix "passing null to non-nullable" [1]

---

.gitignore

As this file is currently not committed and as this package is used as a library, it shouldn't be committed, let's prevent it from accidentally happening anyway.

gitignore: prevent committing composer.lock

---

.gitattributes

* Don't export config files, like the scrutinizer file.
* Remove reference to `.travis.yml` file which no longer exists in the repo.

gitattributes: update export-ignore list

---

.github/workflows/tests.yml

... for lower network resource use and faster builds.
The tests weren't running on PHP 8.1 because PHPUnit 5.x was being installed as not all PHPUnit dependencies have declared PHP 8.1 compatibility yet.
Fixed by running `composer install` with the `--ignore-platform-requirements` option for now.
In the semi-near future, it should be possible to remove the special casing of PHP 8.1.
The default setting for `error_reporting` used by the SetupPHP action is `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT` and `display_errors` is set to `Off`.
For the purposes of CI, I'd recommend running with `-1` and `display_errors=On` to ensure **all** PHP notices are shown.
Without this setting PHP 8.1 deprecation notices are not shown.
* Make the name of the job more descriptive.
* Make the name of …

GH Actions: fix tests not running on PHP 8.1 and other tweaks

---

.github/workflows/tests.yml

Similar to the change made in commit https://github.com/antecedent/patchwork/pull/111/commits/265791163faff4454c9811cde7cbaab9b4b104ca , `zend.assertions` is set to `-1` by default, so needs to be turned on by setting it to `1` for the tests to work.
This fixes the two errors previously identified in #112, ~~but exposes another test which really _does_ fail and that failure can be reproduced locally.~~ **Update: looks like that failure has been fixed in the mean time.**
Ref: https://github.com/shivammathur/setup-php/issues/450
Fixes #112

GH Actions: ensure zend assertions is enabled

---

src/CodeManipulation/Stream.php
tests/parse-ini-file.phpt

In PHP 7 and 8, `parse_ini_file()` calls the wrapper and sets
STREAM_OPEN_FOR_INCLUDE. None the less, we don't want to parse it.
It seems there's no direct way to differentiate such a call from a
`require` or `include` that we do need to process, other than by
checking the stack.
Fixes antecedent#124

Avoid parsing ini files from `parse_ini_file()`

---

.github/workflows/tests.yml

The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2

GH Actions: version update for `ramsey/composer-install`

---

src/CodeManipulation/Actions/RedefinitionOfNew.php
tests/includes/RedefinitionOfNewAsAnonymousClassParameter.php
tests/redefine-new-anonymous-class-paramter.phpt

Fixes https://github.com/antecedent/patchwork/issues/127
This PR adds `T_CLASS` to `hasExtraParentheses()` so that id doesn't count parenthesis around anonymous class parameters as extra parenthesis.

Keep parenthesis around anonymous class parameters

---

.github/workflows/release.yml
.github/workflows/tests.yml

A number of predefined actions have had major release, which warrant an update to the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases

GH Actions: version update for various predefined actions

---

.github/workflows/tests.yml

The `setup-php` action runner will automatically install the appropriate version of Composer depending on the PHP version requested - Composer 2.2 for PHP < 7.2 and Composer 2.3+ for PHP 7.2+.
However, using `tools: none` disables this and falls back to the Composer version which is shipped with the Ubuntu image being used.
Composer 2.3, which was released end of March, has a minimum PHP version of PHP 7.2, so will not work/be available to PHP < 7.2, so we need to ensure that the `setup-php` action runner installs the correct version, otherwise the `composer install` needed for the tests will fail.
Removing the `tools: none` should fix this.
**Note:**
Autoload files generated with Composer 2.3 are no longer compatible with PHP < 5.6, though Composer 2.2 (with a minimum PHP version of PHP …

GH Actions: fix test runs + start testing against PHP 8.2

---

src/CodeManipulation.php
src/CodeManipulation/Stream.php
tests/require-missing-php5.phpt
tests/require-missing.phpt

The stream wrapper was not checking for errors in reading the wrapped file, resulting in `require` treating it as an empty file instead of raising an error as it's supposed to.
This adds the needed error handling.

Fix require of missing files

---

.github/workflows/tests.yml

Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …

GH Actions: bust the cache semi-regularly

---

.github/workflows/tests.yml

PHP 8.2 has been released today :tada: and the `setup-php` action has announced support for PHP 8.3, so adding PHP 8.3 to the matrix and no longer allowing PHP 8.2 to fail the build.
Builds against PHP 8.3 are still allowed to fail for now.

GH Actions: update PHP versions in workflows

---

src/CodeManipulation/Actions/Generic.php
src/CodeManipulation/Actions/RedefinitionOfNew.php
tests/anonymous-class-attribute.phpt
tests/includes/AnonymousClassAttribute.php
tests/redefinition-new-anonymous-class-with-attribute.phpt

Hi, first of all thanks for your work, I didn't know about this library and it could be of great use for a test suite in a project of mine.
I ran into the following issue: when an anonymous class uses a PHP 8 attribute, Patchwork crashes.
I'm adding a failing test to this PR, I currently have no idea where to look to fix this, I'd be glad to help if someone gives me a hint. 🙂 
Have a good day!

Handle anonymous class attribute

---

Patchwork.php
src/CallRerouting.php
src/Exceptions.php
src/Utils.php
tests/inheritance-delayed-redefinition.phpt
tests/internals.phpt
tests/language-constructs.phpt
tests/patchability.phpt
tests/splat.phpt

HHVM dropped support for PHP at the end of 2018.
While testing and basic support for HHVM was enabled in Patchwork, it has basically been broken since then and the tests aren't being run against HHVM anyway.
So, let's formally drop support for it and remove all references to it.
This commit actions this in the following manner:
* Mark dedicated functions/classes related to HHVM as (soft) deprecated.
* Remove all conditionals in the codebase related to HHVM.
Follow-up actions:
* I suggest opening an issue for `2.last` to hard deprecate the functions/classes (i.e. trigger a deprecation notice).
* I also suggest opening an issue for 3.0 to remove the deprecated functions/classes.
Ref: https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
Fixes #139

Remove support for HHVM

---

.github/workflows/tests.yml
composer.json
src/CodeManipulation/Actions/Generic.php
src/CodeManipulation/Stream.php
src/Utils.php
tests/double-colon-class.phpt
tests/generator.phpt
tests/includes/ProxyForInternals.php
tests/php7-parenthesis-removal-bug.phpt
tests/php7-use-function.phpt
tests/php71-void-return-type.phpt
tests/redefine-new-anonymous-class-parameter.phpt
tests/splat.phpt
tests/strict-types.phpt
tests/variadics-bug.phpt
tests/variadics-ref-bug.phpt
tests/void-typed.phpt

This commit drops support for PHP < 7.1 from:
* The GH Actions workflow(s).
* Composer.
* The tests.
... as it is no longer needed now support for PHP < 7.1 has been dropped.
Closes #157

Drop support for PHP < 7.1

---

tests/includes/TestUtils.php

PHP 8.4 deprecates passing `E_USER_ERROR` to `trigger_error()`, suggesting to use exceptions or `exit` instead.
This updates the exception handling in the test suite to avoid the deprecation and still continue to function as before, with the only difference being in the errors which are shown.
```diff
-Fatal error: No exception thrown in * on line *'
+'Fatal error: Uncaught ExceptionNotThrown: No exception thrown in *:*\n
-Fatal error: No exception of type RuntimeExsception thrown in * on line *'
+'Fatal error: Uncaught WrongExceptionThrown: No exception of type RuntimeExsception thrown in *:*\n
```
Ref: https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_passing_e_user_error_to_trigger_error
Related to #157

PHP 8.4 | Silence deprecation for trigger_error()

---

Patchwork.php
src/CallRerouting.php
src/Stack.php
src/Utils.php

PHP 8.4 deprecates implicitly nullable parameters, i.e. typed parameter with a `null` default value, which are not explicitly declared as nullable.
This commit fixes all found instances of that in the codebase.
Ref: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
Related to #157

PHP 8.4 | Fix implicitly nullable parameters

---

.github/workflows/tests.yml

* Builds against PHP 8.4 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.5.
Ref: https://www.php.net/releases/8.4/en.php

GH Actions: PHP 8.4 has been released

---

tests/anonymous-class-attribute.phpt
tests/never-typed.phpt
tests/redefinition-new-anonymous-class-with-attribute.phpt
tests/require-missing-php5.phpt
tests/require-missing.phpt
tests/stream-url-stat.phpt

To unlock PHPUnit side-effect-free in-process `--SKIPIF--` evaluation, we use regular `echo` instead of `die()`.
That way PHPunit can detect whether conditions may be evaluated in the main-process to reduce sub-process creation overhead.
Depends on the work-inprogress of https://github.com/sebastianbergmann/phpunit/pull/5974
----
Running phpunit with the side-effect detecting PR vs. the regular master version, yields the following results in this PR on my windows laptop:
```
$ hyperfine '/c/tools/php83/php ../phpunit/phpunit tests' '/c/tools/php83/php vendor/bin/phpunit tests' --warmup=3
Benchmark 1: C:/tools/php83/php ../phpunit/phpunit tests
Time (mean ± σ):      3.312 s ±  0.020 s    [User: 0.184 s, System: 0.510 s]
Range (min … max):    3.291 s …  3.347 s    10 runs
Benchmark 2: …
```

Don't use die() but echo to skip tests.

---

.gitignore
src/CodeManipulation.php
tests/get-cached-path.phpt

Fixed: "Deprecated: str_getcsv(): the $escape parameter must be provided as its default value will change."

Fix PHP 8.4 deprecation.

---

tests/get-cached-path.phpt

The test as added in PR #170 did not actually hit the PHP 8.4 deprecation notice, which - while it is a useful test for other reasons - makes it an ineffective test for safeguarding the fix from #170, which was about preventing the PHP 8.4 deprecation notice.
This commit updates the test to ensure the fix for the PHP 8.4 deprecation notice is now properly safeguarded.
This can be verified by undoing the change to the `src/CodeManipulation.php` file from #170 and running this test on PHP 8.4. The test will fail and show the deprecation notice. When the change from #170 is re-applied, the test will pass without the deprecation notice.
Includes adding the `===DONE===` markers for consistency with the other tests.

getCachedPath(): improve test

---

src/Config.php

Many possible locations for the patchwork.json were checked repeatedly, now they should only be checked once. This gave me a nice speedup. So hopefully this does not break anything and is helpful for others as well.

Speedup for loading patchwork.json
